[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[build.environment]
  NODE_VERSION = "18.16.0"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
    Access-Control-Allow-Origin = "*"
